### PR TITLE
feat: Make http and file document loaders more configurable.

### PR DESCRIPTION
**Pull request by peacekeeper**
This makes it possible to instantiate ConfigurableDocumentLoader and JsonLDObject, without having to instantiate HttpLoader and FileLoader if they are not needed.

### CODE REVIEW

**Comment by vitorpamplona** [comment]
This works! Thanks!

**Comment by vitorpamplona** [comment]
Of course, I think it would be better if the lib drops the dependency entirely (Let people manually add custom DocumentLoaders for the web and local I/O). But this is a step in the right direction.

**Comment by peacekeeper** [comment]
> I think it would be better if the lib drops the dependency entirely

I'm not sure what dependency to drop, since java.net.http.HttpClient is used directly by [titanium-json-ld](https://github.com/filip26/titanium-json-ld), which is central to this library.

> Let people manually add custom DocumentLoaders

With this change, it should be possible to also add your own DocumentLoaders for http and file, bypassing the default ones altogether.

Do you have any suggestions how to improve this, or should I merge?

**Comment by vitorpamplona** [comment]
Please merge it. I was able to download the branch and test it. It runs beautifully. 

On the dependency, I would argue that `titanium-json-ld` should stop using `java.net.http.HttpClient` as well. But that's for another day. 

Thanks Markus

**Pull request merged**
